services:

  frontend:
    image: fusionpact-devops-challenge-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"
    restart: always

  backend:
    image: fusionpact-devops-challenge-backend
    build:
      context: ./backend
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - prometheus
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/tmp

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    restart: always

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always
    depends_on:
      - prometheus

