deploy:
  needs: build-and-push
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y openssh-client

    - name: Add SSH key
      env:
        SSH_KEY: ${{ secrets.DEPLOY_KEY }}
      run: |
        echo "$SSH_KEY" > deploy_key
        chmod 600 deploy_key

    - name: Copy docker-compose and deploy to EC2
      run: |
        echo "Current working directory:"
        pwd
        echo "Listing files:"
        ls -R

        echo "Copying docker-compose.yml to EC2..."
        scp -i deploy_key -o StrictHostKeyChecking=no ./docker-compose.yml ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }}:/root/fusionpact-devops-challenge/docker-compose.yml

        echo "Connecting to EC2 and deploying..."
        ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
          cd /root/fusionpact-devops-challenge
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker-compose pull
          docker-compose up -d --remove-orphans
        '
