- name: Deploy to EC2
  run: |
    echo "Connecting to EC2 and deploying..."
    ssh -i deploy_key -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.DEPLOY_HOST }} '
      echo "Logging into Docker Hub..."
      sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      echo "Pulling latest Docker images..."
      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fusionpact-frontend:latest
      sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/fusionpact-backend:latest

      echo "Stopping old containers (if any)..."
      sudo docker stop frontend || true
      sudo docker stop backend || true
      sudo docker rm frontend || true
      sudo docker rm backend || true

      echo "Running new containers..."
      sudo docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/fusionpact-frontend:latest
      sudo docker run -d --name backend -p 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/fusionpact-backend:latest

      echo "Deployment completed successfully!"
    '
